[package]
name = "mbta-with-friends"
version = "0.1.0"
authors = ["Matthew Madonna <madonkadonk@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.3.16"
rocket_codegen = "0.3.16"
rocket_contrib = "0.3.16"
